### ISSUE TITLE
Improve User Guide

### ISSUE THREAD

**Issue by aziziazfar** [CS2103AUG2017-F09-B4/main#77]
Overall I like the features that are implemented. Especially the ability to toggle between the different display screens when you click the PersonCard. However, there are instances where it's unclear. Maybe you could add elaborate more about the meeting feature. I only found information regarding nextMeeting and the meeting display which displays the meetings available. Is there a way to add new meetings? I cant seem to find a way to change the theme.

Other than that, the UI is really great, and there are a few bugs that I faced which I will raise in a separate issue. 

- Azizi Azfar T15-B4

**Comment by lh0213** [comment]
- [x] Elaborate more about the meeting feature.

- [x] Theme changing (maybe put in a separate section?)
