### ISSUE TITLE
Bugs for the app

### ISSUE THREAD

**Issue by aziziazfar** [CS2103AUG2017-F09-B4/main#78]
- When i keyed in the command `choose` I'm unable to click anything from the UI. 

![image](https://user-images.githubusercontent.com/31105950/32363557-f5cbc6e6-c0aa-11e7-9c55-c46ebda17e0c.png)

- The comand `choose facebook` the personCard still launches the linkedin login page. 
- `choose maps` doesnt work too. However, `choose meetings` works.
- The listByMostSearched `lms` doesnt seem to display the list properly. I searched "bernice" 10 times but "Alex Yeoh" still comes up at the top of the list for the listByMostSearched.

![image](https://user-images.githubusercontent.com/31105950/32363760-d79486f8-c0ab-11e7-86b6-e37fe7e43ed9.png)

Thats all I caught for now! 👍 

- AziziAzfar T15-B4

**Comment by lh0213** [comment]
- [x] When i keyed in the command choose I'm unable to click anything from the UI.

- [x] Remove `choose facebook` from chooser

- [x] Implement `choose map`

- [x] Bug for `lms`?
